// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
)

// Defines values for AttachmentType.
const (
	Image AttachmentType = "image"
	Video AttachmentType = "video"
)

// Defines values for GetPostsParamsSort.
const (
	Asc  GetPostsParamsSort = "asc"
	Desc GetPostsParamsSort = "desc"
)

// Attachment defines model for Attachment.
type Attachment struct {
	// Src The URL source for the attachment
	Src string `json:"src"`

	// Type The type of attachment
	Type AttachmentType `json:"type"`
}

// AttachmentType The type of attachment
type AttachmentType string

// Content defines model for Content.
type Content struct {
	// Attachments The URLs of the post's attachments
	Attachments *[]Attachment `json:"attachments,omitempty"`

	// Body The body of the post. Required, but c
	Body string `db:"body" json:"body"`
}

// Post defines model for Post.
type Post struct {
	Content  Content `json:"content"`
	Dislikes int     `json:"dislikes"`

	// Id the id of the post
	Id    string `json:"id"`
	Likes int    `json:"likes"`

	// ParentId the id of the parent of the post (if this field is not null, then the post is a comment)
	ParentId *string `db:"parent_id" json:"parent_id,omitempty"`

	// Pfp Author's pfp
	Pfp string `json:"pfp"`

	// Ratioed If this is true, the post should be displayed as a ratioed post (with no content, and locked with no more likes or dislikes)
	Ratioed bool `json:"ratioed"`

	// Timestamp A ISO8601 string that repreesents the exact time that the post was created (time is according to database)
	Timestamp time.Time `json:"timestamp"`

	// Username Author's username
	Username string `json:"username"`
}

// Posts An array of posts
type Posts = []Post

// PostIdParam defines model for PostIdParam.
type PostIdParam = string

// NewPost defines model for NewPost.
type NewPost struct {
	Content Content `json:"content"`

	// ParentId Id of the parent post, if applicable (for comments)
	ParentId *string `json:"parent_id,omitempty"`

	// Username Author's username
	Username string `json:"username"`
}

// GetPostsParams defines parameters for GetPosts.
type GetPostsParams struct {
	// Username Filter posts by author's username. Case sensitive (for now, hope to change soon).
	Username *string `form:"username,omitempty" json:"username,omitempty"`

	// Tag Filter posts by hashtag
	Tag *string `form:"tag,omitempty" json:"tag,omitempty"`

	// Sort Sort posts by date (default desc)
	Sort *GetPostsParamsSort `form:"sort,omitempty" json:"sort,omitempty"`

	// Page The page number to retreive (1-based index)
	Page *int `form:"page,omitempty" json:"page,omitempty"`

	// Limit The number of posts per page (max 100)
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// GetPostsParamsSort defines parameters for GetPosts.
type GetPostsParamsSort string

// CreatePostJSONBody defines parameters for CreatePost.
type CreatePostJSONBody struct {
	Content Content `json:"content"`

	// ParentId Id of the parent post, if applicable (for comments)
	ParentId *string `json:"parent_id,omitempty"`

	// Username Author's username
	Username string `json:"username"`
}

// CreatePostJSONRequestBody defines body for CreatePost for application/json ContentType.
type CreatePostJSONRequestBody CreatePostJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get all posts
	// (GET /posts)
	GetPosts(ctx echo.Context, params GetPostsParams) error
	// Create a new post
	// (POST /posts)
	CreatePost(ctx echo.Context) error
	// Delete a post by ID
	// (DELETE /posts/{postId})
	DeletePostById(ctx echo.Context, postId PostIdParam) error
	// Get a specific post by Id
	// (GET /posts/{postId})
	GetPostById(ctx echo.Context, postId PostIdParam) error
	// Get all comments for a specific post
	// (GET /posts/{postId}/comments)
	GetPostCommentsById(ctx echo.Context, postId PostIdParam) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetPosts converts echo context to params.
func (w *ServerInterfaceWrapper) GetPosts(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetPostsParams
	// ------------- Optional query parameter "username" -------------

	err = runtime.BindQueryParameter("form", true, false, "username", ctx.QueryParams(), &params.Username)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter username: %s", err))
	}

	// ------------- Optional query parameter "tag" -------------

	err = runtime.BindQueryParameter("form", true, false, "tag", ctx.QueryParams(), &params.Tag)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter tag: %s", err))
	}

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameter("form", true, false, "sort", ctx.QueryParams(), &params.Sort)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter sort: %s", err))
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", ctx.QueryParams(), &params.Page)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter page: %s", err))
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", ctx.QueryParams(), &params.Limit)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetPosts(ctx, params)
	return err
}

// CreatePost converts echo context to params.
func (w *ServerInterfaceWrapper) CreatePost(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreatePost(ctx)
	return err
}

// DeletePostById converts echo context to params.
func (w *ServerInterfaceWrapper) DeletePostById(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "postId" -------------
	var postId PostIdParam

	err = runtime.BindStyledParameterWithOptions("simple", "postId", ctx.Param("postId"), &postId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter postId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeletePostById(ctx, postId)
	return err
}

// GetPostById converts echo context to params.
func (w *ServerInterfaceWrapper) GetPostById(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "postId" -------------
	var postId PostIdParam

	err = runtime.BindStyledParameterWithOptions("simple", "postId", ctx.Param("postId"), &postId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter postId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetPostById(ctx, postId)
	return err
}

// GetPostCommentsById converts echo context to params.
func (w *ServerInterfaceWrapper) GetPostCommentsById(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "postId" -------------
	var postId PostIdParam

	err = runtime.BindStyledParameterWithOptions("simple", "postId", ctx.Param("postId"), &postId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter postId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetPostCommentsById(ctx, postId)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/posts", wrapper.GetPosts)
	router.POST(baseURL+"/posts", wrapper.CreatePost)
	router.DELETE(baseURL+"/posts/:postId", wrapper.DeletePostById)
	router.GET(baseURL+"/posts/:postId", wrapper.GetPostById)
	router.GET(baseURL+"/posts/:postId/comments", wrapper.GetPostCommentsById)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9RX3W7cNhN9lQG/D4gNyLvrJiiKvXMctDBQtEaSXgVBwRVHKyYSyZCj2Atj370YUlpp",
	"JW0cN8lF7yRxyDnncP70IHJbO2vQUBDrB+GklzUS+vh2awPdqFv+xq8KQ+61I22NWIu3JYJWYAugEsHZ",
	"QEAWHPrC+hqkAevQSzYGa0QmNG9ykkqRCSNr5Ld4vsiEx0+N9qjEmnyDmQh5ibVkn7RzbBnIa7MV+/0+",
	"GWOgl1ZpjDD/wDtGyo+5NYQmPkrnKp1HAMsPgSE/DM51nuFRe8Jg2/89FmIt/rfshVmmbWF53ZrtMxYK",
	"Df2t1VSYm16UaBS1yUAX0ELaVAhnhfWQ27pmB+ciGxPNRBPQJ53GDq4aKq1/FuBgMtm+H2r6TgwMO6rv",
	"D3vs5gPm1GvbXwR/abkziisimZd1K9SxgsHn8yHy1+vfIdjG5whMmWWR/TkzvNOHuaN4haU92o+mqZmi",
	"ruWW+X3WCu2A3QlF4moWYU+VyMR1HxDHPHvf4STfMEyKZwGGezKhCevwWKQNpD5IIqT3csfvG6t28955",
	"Zeh9Aa9b0hlsGoJ8ongm7i+sdPoitwq3aC7wnry8ILlNBDdinfztxxLGr3Pidcn4rTmmdKj0x7S71kbX",
	"fNOrg0NtCLfo2XIuDWlSn+ai7SsdfCHdR35Syg+r4pnmFx2g0Fgp0AGMJTBNVWVsZHpLHUB2ReH8X91U",
	"j5NvyxXuC9WDV2cUiTUb5+paS0MHiFW6xx1K21QKNghKB1fJHSqQzKU9q9XhTlMJxkIbCRlIo6Cy+UdU",
	"0K3V1iPESwHroYuAgRgbayuUJqaFrjGQrOdIws2bP3/5eXUJiRhQKQk8Oo8YON4ieLyXOQEfk9YPhO5k",
	"gNyjJFRwFtf5avLcehUPs6AkyY0MyMi44UkSa6Ek4QWb/+h6rrlpDqzTVXYZ1t9hF9+DXBrKdip5Z0rb",
	"lYFYfjiyXTT5ykoWi8GkhjEhbQobW7ymipdet8ESEcDV7Q1Xc/QhAbhcrBYrPsg6NNJpsRbPF6vFc2Yv",
	"qYw4lq4Dv8VYaA4jyI0Sa/Eb0m0LfTjnvBtz/VVXhD7RhM0O5Ph+FnAtA0JAEzTpz203N/Yug9I65PjI",
	"S2m2CMFac77opp9PDfpdP/4MLvD0wJM9hq6UoSS5PeEjrTzh+DfWU384RzScKSxkUxGw5fkJR8F6OvLU",
	"NWYZuOnw1tmuPNfFnNwimKbeoGctPZLHKPPlBeecAm0U3p9C4tIg0CM5lPbLaWmfB9D67mKdp9oE6qyW",
	"93C5Wp3yXela05zgvcP3nMrBWRNS4/lptXrS5PqNWTeuk5UO1Cd1nPiaupZ+lxIGZFV1a1kc2Kd5dR0r",
	"5W3qsP10vjsF8miAX3bT+36iy+WTdHlcjil9/n4o9KHJcwyhaKpqNxIiMQQJBu/SKMHrqdwsH9JvzD4V",
	"zQoJpxK9it/Z3ctd/OMZFaA58L3JcvgjNhNAL6b1OjJLaMbMMvHi5A6eTArbGDUSIOEHmdrjZgc3r/ig",
	"L5XZH0F09V0jIsyFxNvDDMATCU8EW/0ZTUv46crFHILgMNeFznv91FwILbs/wsd62HVr9x8WuaN6+C38",
	"7qpX1bGT0TUwsP0/AQAA///HVZrHAREAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
