// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
)

// Defines values for AttachmentType.
const (
	Image AttachmentType = "image"
	Video AttachmentType = "video"
)

// Defines values for GetPostsParamsSort.
const (
	Asc  GetPostsParamsSort = "asc"
	Desc GetPostsParamsSort = "desc"
)

// Attachment defines model for Attachment.
type Attachment struct {
	// Src The URL source for the attachment
	Src string `json:"src"`

	// Type The type of attachment
	Type AttachmentType `json:"type"`
}

// AttachmentType The type of attachment
type AttachmentType string

// Content defines model for Content.
type Content struct {
	// Attachments The URLs of the post's attachments
	Attachments *[]Attachment `json:"attachments,omitempty"`

	// Body The body of the post. Required, but c
	Body string `db:"body" json:"body"`
}

// Post defines model for Post.
type Post struct {
	Content  Content `json:"content"`
	Dislikes int     `json:"dislikes"`

	// Id the id of the post
	Id    int `json:"id"`
	Likes int `json:"likes"`

	// ParentId the id of the parent of the post (if this field is not null, then the post is a comment)
	ParentId *int `db:"parent_id" json:"parent_id,omitempty"`

	// Pfp Author's pfp
	Pfp string `json:"pfp"`

	// Ratioed If this is true, the post should be displayed as a ratioed post (with no content, and locked with no more likes or dislikes)
	Ratioed bool `json:"ratioed"`

	// Timestamp A ISO8601 string that repreesents the exact time that the post was created (time is according to database)
	Timestamp time.Time `json:"timestamp"`

	// Username Author's username
	Username string `json:"username"`
}

// Posts An array of posts
type Posts = []Post

// NewPost defines model for NewPost.
type NewPost struct {
	Content Content `json:"content"`

	// Username Author's username
	Username string `json:"username"`
}

// GetPostsParams defines parameters for GetPosts.
type GetPostsParams struct {
	// Username Filter posts by author's username
	Username *string `form:"username,omitempty" json:"username,omitempty"`

	// Tag Filter posts by hashtag
	Tag *string `form:"tag,omitempty" json:"tag,omitempty"`

	// Sort Sort posts by date (default desc)
	Sort *GetPostsParamsSort `form:"sort,omitempty" json:"sort,omitempty"`

	// Page The page number to retreive (1-based index)
	Page *int `form:"page,omitempty" json:"page,omitempty"`

	// Limit The number of posts per page (max 100)
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// GetPostsParamsSort defines parameters for GetPosts.
type GetPostsParamsSort string

// CreatePostJSONBody defines parameters for CreatePost.
type CreatePostJSONBody struct {
	Content Content `json:"content"`

	// Username Author's username
	Username string `json:"username"`
}

// CreatePostJSONRequestBody defines body for CreatePost for application/json ContentType.
type CreatePostJSONRequestBody CreatePostJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get all posts
	// (GET /posts)
	GetPosts(ctx echo.Context, params GetPostsParams) error
	// Create a new post
	// (POST /posts)
	CreatePost(ctx echo.Context) error
	// Delete a post by ID
	// (DELETE /posts/{postId})
	DeletePostById(ctx echo.Context, postId string) error
	// Get a specific post by ID
	// (GET /posts/{postId})
	GetPostById(ctx echo.Context, postId string) error
	// Get all comments for a specific post
	// (GET /posts/{postId}/comments)
	GetPostCommentsById(ctx echo.Context, postId string) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetPosts converts echo context to params.
func (w *ServerInterfaceWrapper) GetPosts(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetPostsParams
	// ------------- Optional query parameter "username" -------------

	err = runtime.BindQueryParameter("form", true, false, "username", ctx.QueryParams(), &params.Username)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter username: %s", err))
	}

	// ------------- Optional query parameter "tag" -------------

	err = runtime.BindQueryParameter("form", true, false, "tag", ctx.QueryParams(), &params.Tag)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter tag: %s", err))
	}

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameter("form", true, false, "sort", ctx.QueryParams(), &params.Sort)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter sort: %s", err))
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", ctx.QueryParams(), &params.Page)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter page: %s", err))
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", ctx.QueryParams(), &params.Limit)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetPosts(ctx, params)
	return err
}

// CreatePost converts echo context to params.
func (w *ServerInterfaceWrapper) CreatePost(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreatePost(ctx)
	return err
}

// DeletePostById converts echo context to params.
func (w *ServerInterfaceWrapper) DeletePostById(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "postId" -------------
	var postId string

	err = runtime.BindStyledParameterWithOptions("simple", "postId", ctx.Param("postId"), &postId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter postId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeletePostById(ctx, postId)
	return err
}

// GetPostById converts echo context to params.
func (w *ServerInterfaceWrapper) GetPostById(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "postId" -------------
	var postId string

	err = runtime.BindStyledParameterWithOptions("simple", "postId", ctx.Param("postId"), &postId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter postId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetPostById(ctx, postId)
	return err
}

// GetPostCommentsById converts echo context to params.
func (w *ServerInterfaceWrapper) GetPostCommentsById(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "postId" -------------
	var postId string

	err = runtime.BindStyledParameterWithOptions("simple", "postId", ctx.Param("postId"), &postId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter postId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetPostCommentsById(ctx, postId)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/posts", wrapper.GetPosts)
	router.POST(baseURL+"/posts", wrapper.CreatePost)
	router.DELETE(baseURL+"/posts/:postId", wrapper.DeletePostById)
	router.GET(baseURL+"/posts/:postId", wrapper.GetPostById)
	router.GET(baseURL+"/posts/:postId/comments", wrapper.GetPostCommentsById)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9RX32/bNhD+Vw7cgKaAHNtrMQx+S1NsMDBsQds9FcVAi2ebrUSy5CmJEPh/H46ULNmS",
	"82PJHvYUmeTx7vvu7uPlTuS2dNagoSAWd8Lj9woDvbNKY1z4A2+ubCD+zK0hNPFTOlfoXJK2Zvo1WMNr",
	"Id9iKfnLeevQU3NDz+xHj2uxED9MO6fTZBaml82xXSaqgN7IEtlEYci9duxJLMRFRVvrXwXYH8kE1Q7F",
	"QgTy2mzEbpdFENqjEovPonewDeTL3sauvmJOYndoRL5CXmki4yguiGS+LRsYh/iCz4eBftoi/PXhdwi2",
	"8jnC2nqgLYLs7hkE3i6MXcU7YNeH9miqkiHqUm4Y37VWaHvoTjASd7MY9pCJTFx26TrE2fkOJ/EGDpKB",
	"OhvoVYC+TSY0YRkeqoMe1XtKhPRe1vx7ZVU97p13+t7P4UMDOoNVRZAPGM/E7cRKpye5VbhBM8Fb8nJC",
	"cpMArsQi+dsdUxhXx8hrW+W5HaB0KPS3ZF1qo0vO9GzvUBvCDXo+qdWQDqZAqz4ZYsz0kR6c9Gjo70c4",
	"igf7buFM8w8dYK2xUKADGEtgqqLI+JDpTuoAEnJbcuJfD8N9TK66QDlfbu3u0Q/eHelAz5KGI0iXDQ4d",
	"gOUh6wIPW1sVClYISgdXyBoVSAbT3NUQcaNpC8ZCUwsZSKOgsPk3VNDuldYjxKyA9dDWQI+NlbUFShMb",
	"Q5cYSJZjIGH58c9ffp7NIQED2koCj84jBq64GDzeypyAr0n7e0A3MkDuURIqOIv7nJs8t17FyywoSXIl",
	"A3Jka+tLSWIhlCSc8PExXl9S0bUSWV/WUyrbHuty2BZ4r5v6tJ1q3xFxuzAQBYhL28Ujj9SyKAcDFWNA",
	"2qwtW5OmgreiZ7i4WrKOow/J8fx8dj7jC6xDI50WC/HmfHb+hlFL2kb/U9cGvcEoMaw88WVeKrEQvyFd",
	"NSE76WWJhD6IxedjjL/qgtAneLCqQY7kRfPB7xX6WmQipbOfiG4AGCTwIW9bGbYkNyd8pJ0nXP/Reuou",
	"58qEM4VrWRUEfPL1CUfBejrw1D6xMvDzwaaj7+vYe+TkBsFU5Qo994xH8qivEc7mE+4dBdoovD0ViUtP",
	"ehfJXqPnQ40eD6Dx3dYsOCacgzor5S3MZ7NTvgtdahojvHP4hVsyOGtCekF+ms2eNCE+s3uO9a7Qgbrm",
	"jLNbVZbS16kBQBZFu5cJ17zRh31yGRXvKr2V3RRcnwryYFCetlPybsDL/Em8PEzHED6v7wU7VHmOIayr",
	"oqiPiEgIQYLBmzQU8H6Sj+kd/1mqXRK/AgmHFL2P6+zuXb1UDwkKl+Dy/cE0wE9HurspPBaxXs3HEMTx",
	"KH5f5w/r8O1QviNByfExQZl4e9KCJ5W1rYw64jHRADJhWtWwfM8X3ae+/54vlg2N1/8lY7MXrdAwVqKf",
	"9rMFTzqMb6Ov0TTMPT0FsachOMz1WucHiRiW9LSZKh98Iy+bc8/PVjvIBv7H7/+fuj6a3pz4grksikMn",
	"R8nlwHb/BAAA//8xBz/dqxAAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
